"""Add created_at with server_default

Revision ID: 28045c9a7dbc
Revises: 10ed0e93c7f3
Create Date: 2025-11-29 22:52:49.057140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28045c9a7dbc'
down_revision = '10ed0e93c7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
