"""Add Laptop and LaptopCategory models

Revision ID: 9dff03c455fe
Revises: a402e7cf3117
Create Date: 2025-12-10 00:28:43.223367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dff03c455fe'
down_revision = 'a402e7cf3117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptop_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laptop_categories')),
    sa.UniqueConstraint('category_name', name=op.f('uq_laptop_categories_category_name'))
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['laptop_categories.id'], name=op.f('fk_laptops_category_id_laptop_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_laptops_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_laptops'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptops')
    op.drop_table('laptop_categories')
    # ### end Alembic commands ###
